on: push
      
name: Test
jobs:
  checks:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      uses: cedrickring/golang-action@1.4.1
      env:
        PROJECT_PATH: "."
      with:
        args: go test -v .
